query userAnimeViewsByStatus(
  $status: AnimeViewStatus!
  $options: PaginationInput
) {
  userAnimeViewsByStatus(status: $status, options: $options) {
    hasMore
    total
    fields {
      ...UserAnimeViewFields
    }
  }
}
