query homeAnimes {
  action: categoryPreview(id: 4) {
    ...CategoryPreviewFields
  }

  romance: categoryPreview(id: 3) {
    ...CategoryPreviewFields
  }

  comedie: categoryPreview(id: 1) {
    ...CategoryPreviewFields
  }

  drame: categoryPreview(id: 6) {
    ...CategoryPreviewFields
  }

  sf: categoryPreview(id: 10) {
    ...CategoryPreviewFields
  }

  # userAnimesByViewingStatus(
  #   status: IN_PROGRESS
  #   options: { limit: 10, offset: 0 }
  # ) {
  #   hasMore
  #   fields {
  #     ...UserAnimeStatusFields
  #   }
  # }
}
