fragment UserAnimeViewFields on UserAnimeView {
  id
  status
  anime {
    id
    title
    posterImage
  }
  episodeViews {
    hasBeenSeen
    episode {
      number
    }
  }
  nextEpisodeToSee {
    number
  }
  lastEpisodeSeen {
    number
  }
}
